version: '3'
services:
  addressbook:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - postgresql
    command: sh -c "./wait && ./addressbook"
    environment:
      - WAIT_HOSTS=postgresql:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=2
      - WAIT_HOST_CONNECT_TIMEOUT=5
  postgresql:
    image: "postgres:12.3"
    environment:
      - POSTGRES_PASSWORD=password
